# Generated by Django 4.1.7 on 2023-03-31 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField()),
                ('image_link', models.TextField()),
                ('text', models.TextField()),
                ('refresh', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
