# Generated by Django 4.1.7 on 2023-03-31 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='binance_jwt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='binance_secret_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='binance_uid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
