# Generated by Django 4.1.7 on 2023-04-01 10:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profile_accounts_delete_businessprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='accounts',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
