# Generated by Django 4.1.7 on 2023-04-01 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_profile_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='subscription_active',
            field=models.BooleanField(default=False, verbose_name='Подписка активна?'),
        ),
        migrations.AddField(
            model_name='profile',
            name='type',
            field=models.CharField(choices=[('PR', 'Личный'), ('BS', 'Бизнес')], default='PR', max_length=2),
        ),
    ]
