# Generated by Django 4.1.7 on 2023-04-02 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_profile_subscription_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='binance_jwt',
            new_name='binance_api',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='binance_uid',
        ),
    ]
