# Generated by Django 4.1.7 on 2023-04-02 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_binance_jwt_profile_binance_api_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
