# Generated by Django 4.1.7 on 2023-04-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_payhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payhistory',
            name='id',
        ),
        migrations.AlterField(
            model_name='payhistory',
            name='number',
            field=models.BigAutoField(auto_created=True, editable=False, primary_key=True, serialize=False),
        ),
    ]
